apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  namespace: userservice-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: yashathwani/userservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4141
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:userservicedb;DB_CLOSE_DELAY=-1;MODE=MySQL"
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.h2.Driver"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.H2Dialect"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 4141
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 4141
          initialDelaySeconds: 60
