apiVersion: v1
kind: Service
metadata:
  name: userservice-service
  namespace: userservice-ns
spec:
  type: NodePort
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4141
      nodePort: 30080
